image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080 # api server
    visibility: public
    onOpen: ignore
  - port: 8180 # pgadmin 4
    visibility: public
    onOpen: open-browser
  - port: 5432 # postgres
    onOpen: ignore

vscode:
  extensions:
    - johnpapa.winteriscoming
    - vscode-icons-team.vscode-icons
    - esbenp.prettier-vscode
    - naumovs.color-highlight
    - 42crunch.vscode-openapi
    - dsznajder.es7-react-js-snippets
    - wakatime.vscode-wakatime
    - asciidoctor.asciidoctor-vscode
    - humao.rest-client

tasks:
- before: |
    sudo docker-up &
    mkdir -p /workspace/pgadmin-data
    sudo chown -R 5050:5050 /workspace/pgadmin-data
    sleep 5
  init: docker-compose up --no-start
  command: docker-compose up
- init: yarn install
  command: yarn
