version: '3.8'

services:
  db:
    image: postgres:13-ptbr
    build: ./docker/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest
    networks:
      - freecodecamp
  
  dbadmin:
    image: dpage/pgadmin4
    build: ./docker/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nest@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: nest
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8180:8080"
    depends_on:
      - db
    networks:
      - freecodecamp

networks:
  freecodecamp