@baseURL = {{$processEnv API_SERVER_HOST}}

POST {{baseURL}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=nest@nestjs.com&password=nest
###

POST {{baseURL}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=nest@nestjs.com&password=nest
###



