POST ${{$processEnv API_SERVER_HOST}}/auth/signup
Content-Type: application/x-www-form-urlencoded
Content-Length: 27

email=nest@nestjs.com&password=nest
###
POST ${{$processEnv API_SERVER_HOST}}/auth/signin
###

